#include <bits/stdc++.h>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <iostream>
#include <string>
#include <stdexcept>

using std::cout;
using std::cin;
using std::string;
using std::endl;
using std::sort;
using std::tolower;
using std::setw;
using std::left;
using std::fixed;
using std::setprecision;
using std::vector;
using std::ifstream;
using std::ofstream;
using std::ws;
using std::istream_iterator;
using std::distance;
using std::stringstream;
using std::exception;
